### ISSUE TITLE
Convert apicast bash script to lua

### ISSUE THREAD

**Issue by hallelujah** [3scale/apicast-cli#1]
https://github.com/3scale/apicast/blob/master/apicast/bin/apicast

Would be nice to convert it to Lua code and place it in `bin/apicast-cli`

**Comment by mikz** [comment]
So I've found several issues with converting bash to lua.

1) no way to `exec`
2) no easy way to do shell escape of parameters

Guess there could be some libraries to do this.

**Comment by mikz** [comment]
This is now doable after https://github.com/3scale/apicast-cli/pull/11 is merged. I even thing the exec is going to escape parameters.

**Comment by rubo77** [comment]
So did you manage to convert it to Lua by now? Is there some kind of automation possible?
